import js from "@eslint/js";
import tseslint from "typescript-eslint";
import prettierConfig from "eslint-config-prettier";
import globals from "globals";

/**
 * One flat config for the whole workspace. ESLint 10 resolves files relative to
 * the config's directory, so keeping this at the repo root is what lets a single
 * config cover all four packages.
 *
 * Deliberately the non-type-aware preset: no `project:` pointing at tsconfigs.
 * Type-aware linting is slower and surfaces a different (larger) rule set — if
 * we want it, that's its own change with its own violation count.
 */
export default [
  {
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/build/**",
      "**/coverage/**",
      "**/.turbo/**",
      "**/*.d.ts",
      // Generated by `prisma generate` / `prisma migrate` — not ours to lint.
      "**/prisma/migrations/**",
      "**/.prisma/**",
      "**/generated/**",
      ".claude/**",
      "graphify-out/**",
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    files: ["**/*.{ts,tsx,js,jsx,mjs,cjs}"],
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: "module",
      parserOptions: { ecmaFeatures: { jsx: true } },
      globals: {
        ...globals.node,
        ...globals.browser,
        ...globals.jest,
      },
    },
    rules: {
      // `_foo` is the codebase's existing convention for a deliberately unused
      // binding (Express's `_next`, ignored destructured fields, mock params).
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
    },
  },

  // Plain .js tooling scripts are CommonJS by necessity — they run under bare
  // Node before any build step, so `require` is the only import they have.
  {
    files: ["**/scripts/**/*.js"],
    languageOptions: { sourceType: "commonjs" },
    rules: { "@typescript-eslint/no-require-imports": "off" },
  },

  // Must stay last: turns off every rule that would fight Prettier.
  prettierConfig,
];
